{"name": "Проверка появления номера нового заказа на экране 'Лента заказов' в разделе 'В работе'", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not callable", "trace": "self = <tests.test_order_page.TestOrderPage object at 0x0000010426698D10>, authorize_user = <pages.main_page.MainPage object at 0x000001042674F3E0>\ncreate_order = None\n\n>   ???\nE   TypeError: 'NoneType' object is not callable\n\ntests\\test_order_page.py:101: TypeError"}, "description": "Создаём заказ и проверяем что его номер отображается на экране 'Лента заказов' в разделе 'В работе'", "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1737466650724, "stop": 1737466650724, "uuid": "e1c833f9-2412-4125-9e9e-58e774cd4052", "historyId": "d196a4d0ff197c26fe4717070786cd1b", "testCaseId": "482e79e860da43b280270f71ad5c519a", "fullName": "tests.test_order_page.TestOrderPage#test_number_appears_in_progress_section_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_page"}, {"name": "subSuite", "value": "TestOrderPage"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "25948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_page"}]}